export const DESTINATIONS_DATA = {
  london: {
    id:"london",
    name: "London",
    code: "LHR",
    country: "United Kingdom",
    price: 0,
    tag: "Popular",
    image: "/photos/London.jpg.jpeg",
    description: `
  
    `,
  },
  dubai: {
    id:"dubai",
    name: "Dubai",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/dubai.jpg.jpeg",
    description: ``,
  },
   paris: {
    id:"paris",
    name: "Paris",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/paris.jpg.jpeg",
    description: `
    <p>

    </p>
    `,
  },
   newyork: {
    id:"newyork",
    name: "New York",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/New-york.jpg.jpeg",
    description: ``,
  },
   losangeles: {
    id:"losangeles",
    name: "Los Angeles",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/losangles.png",
    description: ``,
  },
   sanfrancisco: {
    id:"sanfrancisco",
    name: "San Francisco",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/San Francisco.png",
    description: ``,
  },
   chicago: {
    id:"chicago",
    name: "Chicago",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Chicago.png",
    description: ``,
  },
   miami: {
    id:"miami",
    name: "Miami",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Miami.png",
    description: ``,
  },
   lasvegas: {
    id:"lasvegas",
    name: "Las Vegas",
    code: "DXB",
    country: "UAE",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Las Vegas.png",
    description: ``,
  },
  
};