export const DESTINATIONS_DATA = {
  london: {
    id:"london",
    name: "London",
    canonical:"https://www.business-classflights.com/flight-to/london",
    code: "",
    country: "United Kingdom",
    price: 0,
    tag: "Popular",
    image: "/photos/London.jpg.jpeg",
    description: `
  
    `,
  },
  dubai: {
    id:"dubai",
    name: "Dubai",
    canonical:"https://www.business-classflights.com/flight-to/dubai",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/dubai.jpg.jpeg",
    description: ``,
  },
   paris: {
    id:"paris",
    name: "Paris",
    canonical:"https://www.business-classflights.com/flight-to/paris",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/paris.jpg.jpeg",
    description: `
    <p>

    </p>
    `,
  },
   newyork: {
    id:"newyork",
    name: "New York",
    canonical:"https://www.business-classflights.com/flight-to/newyork",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/New-york.jpg.jpeg",
    description: ``,
  },
   losangeles: {
    id:"losangeles",
    name: "Los Angeles",
    canonical:"https://www.business-classflights.com/flight-to/losangeles",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/losangles.png",
    description: ``,
  },
   sanfrancisco: {
    id:"sanfrancisco",
    name: "San Francisco",
    canonical:"https://www.business-classflights.com/flight-to/sanfrancisco",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/San Francisco.png",
    description: ``,
  },
   chicago: {
    id:"chicago",
    name: "Chicago",
    canonical:"https://www.business-classflights.com/flight-to/chicago",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Chicago.png",
    description: ``,
  },
   miami: {
    id:"miami",
    name: "Miami",
    canonical:"https://www.business-classflights.com/flight-to/miami",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Miami.png",
    description: ``,
  },
   lasvegas: {
    id:"lasvegas",
    name: "Las Vegas",
    canonical:"https://www.business-classflights.com/flight-to/lasvegas",
    code: "",
    country: "",
    price: 0,
    tag: "Luxury Choice",
    image: "/photos/Las Vegas.png",
    description: ``,
  },
  
};