version : "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container-name: business-class-frontend
    restart: always
    ports:
      - "88:88"  
  
